apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  namespace: multi-k8s
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 9090
      targetPort: 5000
